// knowledge-lint — validator for a KOS instance (knowledge/bootstrap/specs/validation.md).
// Nine checks (frontmatter/schema, Purpose header, links, sizes, orphans, category
// integrity, deprecated placement, stale drafts, evidence-for-canon) + --fix mode that
// regenerates Backlinks footers and category AUTO-INDEX blocks.
//
//   node scripts/knowledge-lint.mjs [instanceDir] [--fix]
//
// Exit codes: 0 = clean/warnings only · 1 = errors · 2 = usage/IO failure.
import fs from "node:fs";
import path from "node:path";
import { pathToFileURL } from "node:url";
import Ajv from "ajv";
import addFormats from "ajv-formats";

export const DEFAULT_INSTANCE = path.join("knowledge", "desk-knowledge");
export const CATEGORIES = [
  "concepts",
  "patterns",
  "decisions",
  "lessons",
  "experiments",
  "research",
  "glossary",
  "archive",
];
const EVIDENCE_CATEGORIES = ["lessons", "experiments", "research"];
const STALE_DRAFT_DAYS = 90;
const INDEX_CAP = 200;
const LEAF_ERROR = 650;
const LEAF_WARN = 500;
const BACKLINKS_HEADING = "## Backlinks";
const BACKLINKS_COMMENT = "<!-- AUTO-GENERATED by knowledge-lint --fix. Do not edit. -->";
const AUTO_INDEX_BEGIN = "<!-- AUTO-INDEX:BEGIN -->";
const AUTO_INDEX_END = "<!-- AUTO-INDEX:END -->";

// Frontmatter schema — mirror of knowledge/bootstrap/specs/metadata.md §2.
export const FRONTMATTER_SCHEMA = {
  type: "object",
  required: ["type", "status", "created", "updated"],
  additionalProperties: false,
  properties: {
    type: {
      enum: ["concept", "pattern", "decision", "lesson", "experiment", "research", "glossary"],
    },
    status: { enum: ["draft", "stable", "canonical", "deprecated"] },
    created: { type: "string", format: "date" },
    updated: { type: "string", format: "date" },
    related: { type: "array", items: { type: "string" } },
    depends_on: { type: "array", items: { type: "string" } },
    superseded_by: { type: "string" },
  },
  allOf: [
    {
      if: { properties: { status: { const: "deprecated" } } },
      then: { required: ["superseded_by"] },
    },
    {
      if: { required: ["superseded_by"] },
      then: { properties: { status: { const: "deprecated" } } },
    },
  ],
};

let _validateFm = null;
function validateFm(data) {
  if (!_validateFm) {
    const ajv = new Ajv({ allErrors: true, strict: false });
    addFormats(ajv);
    _validateFm = ajv.compile(FRONTMATTER_SCHEMA);
  }
  const valid = _validateFm(data);
  return {
    valid,
    errors: valid
      ? []
      : _validateFm.errors.map((e) => `${e.instancePath || "(root)"} ${e.message}`),
  };
}

/** Parse the strict YAML subset KOS frontmatter uses (flat keys, inline or dash arrays). */
export function parseFrontmatter(text) {
  const lines = text.split("\n");
  if (lines[0] !== "---") return { data: null, body: text, error: "missing frontmatter" };
  let close = -1;
  for (let i = 1; i < lines.length; i++) {
    if (lines[i] === "---") {
      close = i;
      break;
    }
  }
  if (close === -1) return { data: null, body: text, error: "unclosed frontmatter block" };
  const data = {};
  let pendingList = null; // key currently collecting "- item" lines
  for (let i = 1; i < close; i++) {
    const line = lines[i];
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const item = line.match(/^\s+-\s+(.*)$/);
    if (item && pendingList) {
      data[pendingList].push(stripQuotes(item[1].trim()));
      continue;
    }
    const kv = line.match(/^([A-Za-z_][\w-]*):\s*(.*)$/);
    if (!kv) return { data: null, body: text, error: `unparseable frontmatter line: "${line}"` };
    const [, key, rawVal] = kv;
    const val = rawVal.trim();
    if (val === "") {
      data[key] = [];
      pendingList = key;
    } else if (val.startsWith("[")) {
      if (!val.endsWith("]"))
        return { data: null, body: text, error: `unterminated array for "${key}"` };
      data[key] = val
        .slice(1, -1)
        .split(",")
        .map((s) => stripQuotes(s.trim()))
        .filter(Boolean);
      pendingList = null;
    } else {
      data[key] = stripQuotes(val);
      pendingList = null;
    }
  }
  return { data, body: lines.slice(close + 1).join("\n"), error: null };
}

function stripQuotes(s) {
  return (s.startsWith('"') && s.endsWith('"')) || (s.startsWith("'") && s.endsWith("'"))
    ? s.slice(1, -1)
    : s;
}

/** Remove fenced code blocks and inline code spans (links/wikilinks inside are examples). */
export function stripCode(text) {
  return text.replace(/```[\s\S]*?(```|$)/g, "").replace(/`[^`\n]*`/g, "");
}

/** Extract markdown link targets (skips external/anchor-only; strips #fragments). */
export function extractLinks(text) {
  const out = [];
  const re = /!?\[[^\]]*\]\(([^)]+)\)/g;
  for (const m of stripCode(text).matchAll(re)) {
    let target = m[1].trim().split(/\s+/)[0]; // drop optional "title"
    if (/^(https?:|mailto:|#)/i.test(target)) continue;
    target = target.split("#")[0];
    if (target) out.push(target);
  }
  return out;
}

function hasWikilinks(text) {
  return /\[\[[^\]]+\]\]/.test(stripCode(text));
}

function firstHeading(text) {
  const m = text.match(/^#\s+(.*)$/m);
  return m ? m[1].trim() : null;
}

/** Body above the generated Backlinks footer = the authored region of a note. */
function authoredRegion(text) {
  const idx = text.indexOf(`\n${BACKLINKS_HEADING}`);
  return idx === -1 ? text : text.slice(0, idx);
}

function walkMd(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const p = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (entry.name === ".git" || entry.name === "node_modules" || entry.name === ".obsidian")
        continue;
      out.push(...walkMd(p));
    } else if (entry.name.toLowerCase().endsWith(".md")) {
      out.push(p);
    }
  }
  return out;
}

function toPosix(p) {
  return p.split(path.sep).join("/");
}

/** Load and classify every .md in the instance. */
function loadFiles(root) {
  const files = new Map(); // abs -> record
  for (const abs of walkMd(root)) {
    const rel = toPosix(path.relative(root, abs));
    const raw = fs.readFileSync(abs, "utf8");
    const text = raw.replace(/\r\n/g, "\n");
    const segments = rel.split("/");
    const base = segments[segments.length - 1];
    let role = "note";
    if (base === "index.md") role = "index";
    else if (rel === "PROJECT.md") role = "infra";
    const rec = {
      abs,
      rel,
      role,
      segments,
      text,
      lineCount: text.split("\n").length,
      fm: null,
      body: text,
      authored: text,
      links: [], // resolved absolute targets of authored links (existing or not)
    };
    if (role === "note") {
      rec.fm = parseFrontmatter(text);
      rec.body = rec.fm.body;
      rec.authored = authoredRegion(rec.body);
    }
    files.set(abs, rec);
  }
  return files;
}

/** All authored link targets of a record: frontmatter edges + authored-region body links. */
function authoredTargets(rec) {
  const dir = path.dirname(rec.abs);
  const targets = [];
  if (rec.fm?.data) {
    for (const key of ["related", "depends_on"]) {
      for (const t of rec.fm.data[key] || []) targets.push(t);
    }
    if (rec.fm.data.superseded_by) targets.push(rec.fm.data.superseded_by);
  }
  targets.push(...extractLinks(rec.authored));
  return targets.map((t) => ({ target: t, resolved: path.resolve(dir, t) }));
}

/** Run all checks over one instance folder. Returns { errors, warnings, fileCount }. */
export function lintInstance(root, { now = new Date() } = {}) {
  const errors = [];
  const warnings = [];
  const err = (file, msg) => errors.push({ file, msg });
  const warn = (file, msg) => warnings.push({ file, msg });

  const files = loadFiles(root);
  const byRel = new Map([...files.values()].map((r) => [r.rel, r]));
  const notes = [...files.values()].filter((r) => r.role === "note");

  const globalIndex = byRel.get("index.md");
  if (!globalIndex) err(".", "missing global index.md at the instance root");

  for (const rec of files.values()) {
    // 4 — size caps by role
    if (rec.role === "index") {
      if (rec.lineCount > INDEX_CAP)
        err(rec.rel, `index is ${rec.lineCount} lines (hard cap ${INDEX_CAP})`);
    } else if (rec.lineCount > LEAF_ERROR) {
      err(rec.rel, `${rec.lineCount} lines (> ${LEAF_ERROR}) — split required (semantic clusters)`);
    } else if (rec.lineCount >= LEAF_WARN) {
      warn(rec.rel, `${rec.lineCount} lines (${LEAF_WARN}–${LEAF_ERROR}) — split if ≥2 semantic clusters`);
    }

    // 3 — wikilinks + link resolution (whole file; --fix regenerates stale footers)
    if (hasWikilinks(rec.text)) err(rec.rel, "contains [[wikilinks]] — use relative markdown links");
    const dir = path.dirname(rec.abs);
    const fmPaths = [];
    if (rec.fm?.data) {
      for (const key of ["related", "depends_on"]) fmPaths.push(...(rec.fm.data[key] || []));
      if (rec.fm.data.superseded_by) fmPaths.push(rec.fm.data.superseded_by);
    }
    for (const target of [...fmPaths, ...extractLinks(rec.body)]) {
      if (/^(https?:|mailto:|#)/i.test(target)) continue;
      const clean = target.split("#")[0];
      if (!clean) continue;
      if (!fs.existsSync(path.resolve(dir, clean))) err(rec.rel, `broken link: ${target}`);
    }

    if (rec.role !== "note") continue;

    // 6 — placement: notes live exactly one level deep, in a known category
    if (rec.segments.length !== 2) {
      err(rec.rel, "note must live exactly one level deep (<category>/<note>.md)");
    } else if (!CATEGORIES.includes(rec.segments[0])) {
      err(rec.rel, `unknown category "${rec.segments[0]}" (allowed: ${CATEGORIES.join(", ")})`);
    }

    // 1 — frontmatter + schema
    if (rec.fm.error || !rec.fm.data) {
      err(rec.rel, `frontmatter: ${rec.fm.error || "missing"}`);
    } else {
      const { valid, errors: fmErrors } = validateFm(rec.fm.data);
      if (!valid) for (const e of fmErrors) err(rec.rel, `frontmatter: ${e}`);
    }

    // 2 — Purpose header
    for (const line of ["**Purpose:**", "**When to read:**", "**Do not duplicate:**"]) {
      if (!new RegExp(`^${line.replaceAll("*", "\\*")}`, "m").test(rec.body))
        err(rec.rel, `missing Purpose-header line: ${line}`);
    }

    const fm = rec.fm.data || {};

    // 7 — deprecated placement
    if (fm.status === "deprecated" && rec.segments[0] !== "archive")
      warn(rec.rel, "deprecated but not yet moved to archive/");

    // 8 — stale draft
    if (fm.status === "draft" && fm.updated) {
      const age = (now - new Date(`${fm.updated}T00:00:00Z`)) / 86400000;
      if (age > STALE_DRAFT_DAYS)
        warn(rec.rel, `draft untouched for ${Math.floor(age)} days (> ${STALE_DRAFT_DAYS}) — verify, evolve, or deprecate`);
    }

    // 5b — thin linking (authored outbound edges that resolve)
    const outbound = new Set(
      authoredTargets(rec)
        .filter(({ resolved }) => resolved !== rec.abs && fs.existsSync(resolved))
        .map(({ resolved }) => resolved)
    );
    if (outbound.size < 2) warn(rec.rel, `only ${outbound.size} outbound link(s) — connect it if a real edge exists`);

    // 9 — evidence for canon
    if (fm.status === "canonical" && ["pattern", "decision"].includes(fm.type)) {
      const hasEvidence = authoredTargets(rec).some(({ resolved }) => {
        const rel = toPosix(path.relative(root, resolved));
        return !rel.startsWith("..") && EVIDENCE_CATEGORIES.includes(rel.split("/")[0]);
      });
      if (!hasEvidence)
        err(rec.rel, "canonical pattern/decision must link ≥1 lessons/, experiments/, or research/ note");
    }
  }

  // 6 — category integrity: index exists + every note listed in it
  const categoryDirs = new Set(notes.filter((n) => n.segments.length === 2).map((n) => n.segments[0]));
  for (const cat of categoryDirs) {
    const idx = byRel.get(`${cat}/index.md`);
    if (!idx) {
      err(`${cat}/`, "category folder has no index.md");
      continue;
    }
    const listed = new Set(
      extractLinks(idx.text).map((t) => path.resolve(path.dirname(idx.abs), t.split("#")[0]))
    );
    for (const note of notes.filter((n) => n.segments[0] === cat && n.segments.length === 2)) {
      if (!listed.has(note.abs)) err(note.rel, `not listed in ${cat}/index.md (run --fix)`);
    }
  }

  // 5a — reachability from the global index (authored links only)
  if (globalIndex) {
    const visited = new Set();
    const queue = [globalIndex.abs];
    while (queue.length) {
      const abs = queue.pop();
      if (visited.has(abs)) continue;
      visited.add(abs);
      const rec = files.get(abs);
      if (!rec) continue; // link out of the instance — fine, not traversed
      for (const { resolved } of authoredTargets(rec)) {
        if (files.has(resolved) && !visited.has(resolved)) queue.push(resolved);
      }
    }
    for (const rec of files.values()) {
      if (!visited.has(rec.abs))
        err(rec.rel, "orphan: unreachable from index.md by following links");
    }
  }

  return { errors, warnings, fileCount: files.size };
}

/** --fix: regenerate Backlinks footers + category AUTO-INDEX blocks. Returns changed rel paths. */
export function fixInstance(root) {
  const files = loadFiles(root);
  const notes = [...files.values()].filter((r) => r.role === "note");
  const changed = [];

  // Inbound map: note -> [notes that link to it] (authored edges between notes only).
  const inbound = new Map(notes.map((n) => [n.abs, []]));
  for (const src of notes) {
    const seen = new Set();
    for (const { resolved } of authoredTargets(src)) {
      if (resolved === src.abs || !inbound.has(resolved) || seen.has(resolved)) continue;
      seen.add(resolved);
      inbound.get(resolved).push(src);
    }
  }

  for (const note of notes) {
    const sources = inbound
      .get(note.abs)
      .sort((a, b) => a.rel.localeCompare(b.rel))
      .map((src) => {
        const relPath = toPosix(path.relative(path.dirname(note.abs), src.abs));
        return `- [${firstHeading(src.body) || src.rel}](${relPath})`;
      });
    const lines = sources.length ? sources : ["- _none yet_"];
    const footer = `${BACKLINKS_HEADING}\n${BACKLINKS_COMMENT}\n${lines.join("\n")}\n`;
    const idx = note.text.indexOf(`\n${BACKLINKS_HEADING}`);
    const next =
      idx === -1
        ? `${note.text.replace(/\n*$/, "")}\n\n${footer}`
        : `${note.text.slice(0, idx + 1)}${footer}`;
    if (next !== fs.readFileSync(note.abs, "utf8")) {
      fs.writeFileSync(note.abs, next);
      changed.push(note.rel);
    }
  }

  // Category AUTO-INDEX blocks.
  const byCat = new Map();
  for (const n of notes) {
    if (n.segments.length !== 2) continue;
    if (!byCat.has(n.segments[0])) byCat.set(n.segments[0], []);
    byCat.get(n.segments[0]).push(n);
  }
  for (const [cat, catNotes] of byCat) {
    const idx = files.get(path.join(root, cat, "index.md"));
    if (!idx) continue; // missing index is a lint error, not --fix territory
    const rows = catNotes
      .sort((a, b) => a.rel.localeCompare(b.rel))
      .map((n) => {
        const fm = n.fm?.data || {};
        const title = firstHeading(n.body) || n.segments[1];
        return `- [${title}](${n.segments[1]}) — ${fm.type || "?"}, ${fm.status || "?"}`;
      });
    const block = `${AUTO_INDEX_BEGIN}\n${rows.join("\n") || "- _none yet_"}\n${AUTO_INDEX_END}`;
    let next;
    const begin = idx.text.indexOf(AUTO_INDEX_BEGIN);
    const end = idx.text.indexOf(AUTO_INDEX_END);
    if (begin !== -1 && end !== -1 && end > begin) {
      next = idx.text.slice(0, begin) + block + idx.text.slice(end + AUTO_INDEX_END.length);
    } else {
      next = `${idx.text.replace(/\n*$/, "")}\n\n${block}\n`;
    }
    if (next !== fs.readFileSync(idx.abs, "utf8")) {
      fs.writeFileSync(idx.abs, next);
      changed.push(idx.rel);
    }
  }
  return { changed };
}

function main() {
  const args = process.argv.slice(2);
  const fix = args.includes("--fix");
  const dirArg = args.find((a) => !a.startsWith("--"));
  const root = path.resolve(dirArg || DEFAULT_INSTANCE);
  if (!fs.existsSync(root) || !fs.statSync(root).isDirectory()) {
    console.error(`knowledge-lint: instance dir not found: ${root}`);
    process.exit(2);
  }
  try {
    if (fix) {
      const { changed } = fixInstance(root);
      for (const rel of changed) console.log(`FIXED ${rel}`);
    }
    const { errors, warnings, fileCount } = lintInstance(root);
    for (const e of errors) console.log(`ERROR ${e.file} :: ${e.msg}`);
    for (const w of warnings) console.log(`WARN  ${w.file} :: ${w.msg}`);
    console.log(
      `knowledge-lint: ${errors.length} error(s), ${warnings.length} warning(s) across ${fileCount} file(s)`
    );
    process.exit(errors.length ? 1 : 0);
  } catch (e) {
    console.error(`knowledge-lint: ${e.message}`);
    process.exit(2);
  }
}

if (process.argv[1] && pathToFileURL(process.argv[1]).href === import.meta.url) main();
